# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13model_service.proto\"N\n\x0eResultsRequest\x12\x11\n\timage_url\x18\x01 \x01(\t\x12\x14\n\x0c\x63lass_labels\x18\x02 \x03(\t\x12\x13\n\x0b\x63onfidences\x18\x03 \x03(\x02\"3\n\x0fResultsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2A\n\x0cModelService\x12\x31\n\x0cStoreResults\x12\x0f.ResultsRequest\x1a\x10.ResultsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RESULTSREQUEST']._serialized_start=23
  _globals['_RESULTSREQUEST']._serialized_end=101
  _globals['_RESULTSRESPONSE']._serialized_start=103
  _globals['_RESULTSRESPONSE']._serialized_end=154
  _globals['_MODELSERVICE']._serialized_start=156
  _globals['_MODELSERVICE']._serialized_end=221
# @@protoc_insertion_point(module_scope)
