# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import model_service_pb2 as model__service__pb2


class ModelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreResults = channel.stream_stream(
                '/ModelService/StoreResults',
                request_serializer=model__service__pb2.ResultsRequest.SerializeToString,
                response_deserializer=model__service__pb2.ResultsResponse.FromString,
                )
        self.StoreMetrics = channel.unary_unary(
                '/ModelService/StoreMetrics',
                request_serializer=model__service__pb2.MetricsRequest.SerializeToString,
                response_deserializer=model__service__pb2.MetricsResponse.FromString,
                )


class ModelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StoreResults(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreResults': grpc.stream_stream_rpc_method_handler(
                    servicer.StoreResults,
                    request_deserializer=model__service__pb2.ResultsRequest.FromString,
                    response_serializer=model__service__pb2.ResultsResponse.SerializeToString,
            ),
            'StoreMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreMetrics,
                    request_deserializer=model__service__pb2.MetricsRequest.FromString,
                    response_serializer=model__service__pb2.MetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreResults(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/ModelService/StoreResults',
            model__service__pb2.ResultsRequest.SerializeToString,
            model__service__pb2.ResultsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StoreMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ModelService/StoreMetrics',
            model__service__pb2.MetricsRequest.SerializeToString,
            model__service__pb2.MetricsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
