# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import neo4j_service_pb2 as neo4j__service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in neo4j_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Neo4jServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreResult = channel.unary_unary(
                '/Neo4jService/StoreResult',
                request_serializer=neo4j__service__pb2.ClassificationResult.SerializeToString,
                response_deserializer=neo4j__service__pb2.StoreResultResponse.FromString,
                _registered_method=True)
        self.StoreMetrics = channel.unary_unary(
                '/Neo4jService/StoreMetrics',
                request_serializer=neo4j__service__pb2.MetricsResult.SerializeToString,
                response_deserializer=neo4j__service__pb2.StoreResultResponse.FromString,
                _registered_method=True)
        self.GetFeedback = channel.unary_unary(
                '/Neo4jService/GetFeedback',
                request_serializer=neo4j__service__pb2.FeedbackRequest.SerializeToString,
                response_deserializer=neo4j__service__pb2.FeedbackResponse.FromString,
                _registered_method=True)


class Neo4jServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StoreResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Neo4jServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreResult': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreResult,
                    request_deserializer=neo4j__service__pb2.ClassificationResult.FromString,
                    response_serializer=neo4j__service__pb2.StoreResultResponse.SerializeToString,
            ),
            'StoreMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreMetrics,
                    request_deserializer=neo4j__service__pb2.MetricsResult.FromString,
                    response_serializer=neo4j__service__pb2.StoreResultResponse.SerializeToString,
            ),
            'GetFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeedback,
                    request_deserializer=neo4j__service__pb2.FeedbackRequest.FromString,
                    response_serializer=neo4j__service__pb2.FeedbackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Neo4jService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Neo4jService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Neo4jService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Neo4jService/StoreResult',
            neo4j__service__pb2.ClassificationResult.SerializeToString,
            neo4j__service__pb2.StoreResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Neo4jService/StoreMetrics',
            neo4j__service__pb2.MetricsResult.SerializeToString,
            neo4j__service__pb2.StoreResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Neo4jService/GetFeedback',
            neo4j__service__pb2.FeedbackRequest.SerializeToString,
            neo4j__service__pb2.FeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
