# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: neo4j_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13neo4j_service.proto\"R\n\x14\x43lassificationResult\x12\x13\n\x0b\x63lass_label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x11\n\timage_url\x18\x03 \x01(\t\"&\n\x13StoreResultResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"$\n\x0f\x46\x65\x65\x64\x62\x61\x63kRequest\x12\x11\n\tresult_id\x18\x01 \x01(\t\"$\n\x10\x46\x65\x65\x64\x62\x61\x63kResponse\x12\x10\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x01 \x01(\t2~\n\x0cNeo4jService\x12:\n\x0bStoreResult\x12\x15.ClassificationResult\x1a\x14.StoreResultResponse\x12\x32\n\x0bGetFeedback\x12\x10.FeedbackRequest\x1a\x11.FeedbackResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'neo4j_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLASSIFICATIONRESULT']._serialized_start=23
  _globals['_CLASSIFICATIONRESULT']._serialized_end=105
  _globals['_STORERESULTRESPONSE']._serialized_start=107
  _globals['_STORERESULTRESPONSE']._serialized_end=145
  _globals['_FEEDBACKREQUEST']._serialized_start=147
  _globals['_FEEDBACKREQUEST']._serialized_end=183
  _globals['_FEEDBACKRESPONSE']._serialized_start=185
  _globals['_FEEDBACKRESPONSE']._serialized_end=221
  _globals['_NEO4JSERVICE']._serialized_start=223
  _globals['_NEO4JSERVICE']._serialized_end=349
# @@protoc_insertion_point(module_scope)
