version: '3.8'
services:
  frontend:
    build:
      context: ..  
      dockerfile: docker/frontend/Dockerfile  
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge