version: '3.8'

services:
  frontend:
    build:
      context: ..  
      dockerfile: docker/frontend/Dockerfile  
    ports:
      - "3000:3000"
    networks:
      - app_network

  backend:
    build:
      context: ..  
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
